version: "3.8"

services:
  cloudisense:
    image: rajdeeprath/cloudisense:latest
    container_name: cloudisense
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: 
      - .env
    volumes:
      - logs:/root/filesystem/logs

volumes:
  logs:
    driver: local
