# .github/workflows/build.yml
name: Build and Push CloudiSENSE Demo Image to Dockerhub

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'CloudiSENSE version to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docker repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Versioned Demo Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg CLOUDISENSE_VERSION=${{ github.event.inputs.version }} \
            -t rajdeeprath/cloudisense:${{ github.event.inputs.version }} \
            --push \
            .

      - name: Tag image as latest (multi-arch)
        run: |
          docker buildx imagetools create \
            --tag rajdeeprath/cloudisense:latest \
            rajdeeprath/cloudisense:${{ github.event.inputs.version }}
